### ISSUE TITLE
Issues front

### ISSUE THREAD

**Issue by Lautarotetamusa** [agus32/react-native-agribusiness#1]
# Chat

- [x] En la aplicacion cuando abris un chat queda como loading... y nunca carga los mensajes.

# Colaborador

- [x] El boton de notificaciones lleva a eventos.

## Solicitud
- [x] Si un colaborador pone para crear una pero no tiene a nadie que la reciba no se muestra la lista y parece que no anduvo.

- [x] Cuando seleccionas un colaborador que para que reciba la solicitud no aparece a quien seleccionaste.

- [x] Agregar los cargos de las personas a las que se puede solicitar en el desplegable.
- [x] persona/${parsedUser.cedula}/solicitables` incluir cargo en la response. (backend)

## Cotizacion
- [x] Poner la cedula al lado del nombre del cliente que se solicita.

- [x] Si pones una cantidad de dias mayor a 9 tira error. (problema back)

- [x] Cambiar el orden en el que se muestran las cotizaciones, poner las mas nuevas primero

-  [x] El pdf se puede reenviar pero no descargar en el telefono.

### Galeria compartida
- Aparece este error: Key "cancelled" in the image picker result is deprecated and will be removed in SDK 48, use "canceled" instead (Es una warning ya fue)

- [x] Subir el maximo peso permitido de las imagenes.

- [x] Cuando reenvias la imagen se manda mal. el tipo de imagen se pone como undefined.

- [x] No se puede abrir la imagen.

### Fichas tecnicas
- [x] No se puede descargar.

# Admin
- [x] Cuando se sube una imagen de portada no se guarda bien. Formato .undefined
Desde postman se sube bien, es algun problema de la app.

- [x] El producto tiene imagen de portada pero igual no se ve.

- [x] Sacar botones menu y notificaciones que no hacen nada.

## Eventos
- [ ] (Back) Cuando se actualiza un evento sale que nada es distinto a lo que ya existia en la DB. 

- [x] Las imagenes no se ven. (en clientes si se ve)

- [x] No se suben bien las imagenes desde la app, el formato se guarda como undefined.

# Clientes

- [x] Poner las imagenes de articulos tecnicos y directorio como los botones. Cuesta darse cuenta que hay que apretar el texto.

## Productos
- [x] Cuando vas a productos no carga nada. En web si aparecen las imagenes pero en la aplicación no aparecen. (supongo que es un error del tamaño de las fotos)

**Comment by agus32** [comment]
arreglado

**Comment by Lautarotetamusa** [comment]
Muy buen trabajo!
